import os
import struct

actorsFolder = "src/actors/"
gActorOverlayTableVAddr = 0x50CD84

actorsTable = (
    "ACTOR_PLAYER",
    "ACTOR_UNSET_1",
    "ACTOR_EN_TEST",
    "ACTOR_UNSET_3",
    "ACTOR_EN_GIRLA",
    "ACTOR_UNSET_5",
    "ACTOR_UNSET_6",
    "ACTOR_EN_PART",
    "ACTOR_EN_LIGHT",
    "ACTOR_EN_DOOR",
    "ACTOR_EN_BOX",
    "ACTOR_BG_DY_YOSEIZO",
    "ACTOR_BG_HIDAN_FIREWALL",
    "ACTOR_EN_POH",
    "ACTOR_EN_OKUTA",
    "ACTOR_BG_YDAN_SP",
    "ACTOR_EN_BOM",
    "ACTOR_EN_WALLMAS",
    "ACTOR_EN_DODONGO",
    "ACTOR_EN_FIREFLY",
    "ACTOR_EN_HORSE",
    "ACTOR_EN_ITEM00",
    "ACTOR_EN_ARROW",
    "ACTOR_UNSET_17",
    "ACTOR_EN_ELF",
    "ACTOR_EN_NIW",
    "ACTOR_UNSET_1A",
    "ACTOR_EN_TITE",
    "ACTOR_EN_REEBA",
    "ACTOR_EN_PEEHAT",
    "ACTOR_EN_BUTTE",
    "ACTOR_UNSET_1F",
    "ACTOR_EN_INSECT",
    "ACTOR_EN_FISH",
    "ACTOR_UNSET_22",
    "ACTOR_EN_HOLL",
    "ACTOR_EN_SCENE_CHANGE",
    "ACTOR_EN_ZF",
    "ACTOR_EN_HATA",
    "ACTOR_BOSS_DODONGO",
    "ACTOR_BOSS_GOMA",
    "ACTOR_EN_ZL1",
    "ACTOR_EN_VIEWER",
    "ACTOR_EN_GOMA",
    "ACTOR_BG_PUSHBOX",
    "ACTOR_EN_BUBBLE",
    "ACTOR_DOOR_SHUTTER",
    "ACTOR_EN_DODOJR",
    "ACTOR_EN_BDFIRE",
    "ACTOR_UNSET_31",
    "ACTOR_EN_BOOM",
    "ACTOR_EN_TORCH2",
    "ACTOR_EN_BILI",
    "ACTOR_EN_TP",
    "ACTOR_UNSET_36",
    "ACTOR_EN_ST",
    "ACTOR_EN_BW",
    "ACTOR_EN_A_OBJ",
    "ACTOR_EN_EIYER",
    "ACTOR_EN_RIVER_SOUND",
    "ACTOR_EN_HORSE_NORMAL",
    "ACTOR_EN_OSSAN",
    "ACTOR_BG_TREEMOUTH",
    "ACTOR_BG_DODOAGO",
    "ACTOR_BG_HIDAN_DALM",
    "ACTOR_BG_HIDAN_HROCK",
    "ACTOR_EN_HORSE_GANON",
    "ACTOR_BG_HIDAN_ROCK",
    "ACTOR_BG_HIDAN_RSEKIZOU",
    "ACTOR_BG_HIDAN_SEKIZOU",
    "ACTOR_BG_HIDAN_SIMA",
    "ACTOR_BG_HIDAN_SYOKU",
    "ACTOR_EN_XC",
    "ACTOR_BG_HIDAN_CURTAIN",
    "ACTOR_BG_SPOT00_HANEBASI",
    "ACTOR_EN_MB",
    "ACTOR_EN_BOMBF",
    "ACTOR_EN_ZL2",
    "ACTOR_BG_HIDAN_FSLIFT",
    "ACTOR_EN_OE2",
    "ACTOR_BG_YDAN_HASI",
    "ACTOR_BG_YDAN_MARUTA",
    "ACTOR_BOSS_GANONDROF",
    "ACTOR_UNSET_53",
    "ACTOR_EN_AM",
    "ACTOR_EN_DEKUBABA",
    "ACTOR_EN_M_FIRE1",
    "ACTOR_EN_M_THUNDER",
    "ACTOR_BG_DDAN_JD",
    "ACTOR_BG_BREAKWALL",
    "ACTOR_EN_JJ",
    "ACTOR_EN_HORSE_ZELDA",
    "ACTOR_BG_DDAN_KD",
    "ACTOR_DOOR_WARP1",
    "ACTOR_OBJ_SYOKUDAI",
    "ACTOR_ITEM_B_HEART",
    "ACTOR_EN_DEKUNUTS",
    "ACTOR_BG_MENKURI_KAITEN",
    "ACTOR_BG_MENKURI_EYE",
    "ACTOR_EN_VALI",
    "ACTOR_BG_MIZU_MOVEBG",
    "ACTOR_BG_MIZU_WATER",
    "ACTOR_ARMS_HOOK",
    "ACTOR_EN_FHG",
    "ACTOR_BG_MORI_HINERI",
    "ACTOR_EN_BB",
    "ACTOR_BG_TOKI_HIKARI",
    "ACTOR_EN_YUKABYUN",
    "ACTOR_BG_TOKI_SWD",
    "ACTOR_EN_FHG_FIRE",
    "ACTOR_BG_MJIN",
    "ACTOR_BG_HIDAN_KOUSI",
    "ACTOR_DOOR_TOKI",
    "ACTOR_BG_HIDAN_HAMSTEP",
    "ACTOR_EN_BIRD",
    "ACTOR_UNSET_73",
    "ACTOR_UNSET_74",
    "ACTOR_UNSET_75",
    "ACTOR_UNSET_76",
    "ACTOR_EN_WOOD02",
    "ACTOR_UNSET_78",
    "ACTOR_UNSET_79",
    "ACTOR_UNSET_7A",
    "ACTOR_UNSET_7B",
    "ACTOR_EN_LIGHTBOX",
    "ACTOR_EN_PU_BOX",
    "ACTOR_UNSET_7E",
    "ACTOR_UNSET_7F",
    "ACTOR_EN_TRAP",
    "ACTOR_EN_AROW_TRAP",
    "ACTOR_EN_VASE",
    "ACTOR_UNSET_83",
    "ACTOR_EN_TA",
    "ACTOR_EN_TK",
    "ACTOR_BG_MORI_BIGST",
    "ACTOR_BG_MORI_ELEVATOR",
    "ACTOR_BG_MORI_KAITENKABE",
    "ACTOR_BG_MORI_RAKKATENJO",
    "ACTOR_EN_VM",
    "ACTOR_DEMO_EFFECT",
    "ACTOR_DEMO_KANKYO",
    "ACTOR_BG_HIDAN_FWBIG",
    "ACTOR_EN_FLOORMAS",
    "ACTOR_EN_HEISHI1",
    "ACTOR_EN_RD",
    "ACTOR_EN_PO_SISTERS",
    "ACTOR_BG_HEAVY_BLOCK",
    "ACTOR_BG_PO_EVENT",
    "ACTOR_OBJ_MURE",
    "ACTOR_EN_SW",
    "ACTOR_BOSS_FD",
    "ACTOR_OBJECT_KANKYO",
    "ACTOR_EN_DU",
    "ACTOR_EN_FD",
    "ACTOR_EN_HORSE_LINK_CHILD",
    "ACTOR_DOOR_ANA",
    "ACTOR_BG_SPOT02_OBJECTS",
    "ACTOR_BG_HAKA",
    "ACTOR_MAGIC_WIND",
    "ACTOR_MAGIC_FIRE",
    "ACTOR_UNSET_A0",
    "ACTOR_EN_RU1",
    "ACTOR_BOSS_FD2",
    "ACTOR_EN_FD_FIRE",
    "ACTOR_EN_DH",
    "ACTOR_EN_DHA",
    "ACTOR_EN_RL",
    "ACTOR_EN_ENCOUNT1",
    "ACTOR_DEMO_DU",
    "ACTOR_DEMO_IM",
    "ACTOR_DEMO_TRE_LGT",
    "ACTOR_EN_FW",
    "ACTOR_BG_VB_SIMA",
    "ACTOR_EN_VB_BALL",
    "ACTOR_BG_HAKA_MEGANE",
    "ACTOR_BG_HAKA_MEGANEBG",
    "ACTOR_BG_HAKA_SHIP",
    "ACTOR_BG_HAKA_SGAMI",
    "ACTOR_UNSET_B2",
    "ACTOR_EN_HEISHI2",
    "ACTOR_EN_ENCOUNT2",
    "ACTOR_EN_FIRE_ROCK",
    "ACTOR_EN_BROB",
    "ACTOR_MIR_RAY",
    "ACTOR_BG_SPOT09_OBJ",
    "ACTOR_BG_SPOT18_OBJ",
    "ACTOR_BOSS_VA",
    "ACTOR_BG_HAKA_TUBO",
    "ACTOR_BG_HAKA_TRAP",
    "ACTOR_BG_HAKA_HUTA",
    "ACTOR_BG_HAKA_ZOU",
    "ACTOR_BG_SPOT17_FUNEN",
    "ACTOR_EN_SYATEKI_ITM",
    "ACTOR_EN_SYATEKI_MAN",
    "ACTOR_EN_TANA",
    "ACTOR_EN_NB",
    "ACTOR_BOSS_MO",
    "ACTOR_EN_SB",
    "ACTOR_EN_BIGOKUTA",
    "ACTOR_EN_KAREBABA",
    "ACTOR_BG_BDAN_OBJECTS",
    "ACTOR_DEMO_SA",
    "ACTOR_DEMO_GO",
    "ACTOR_EN_IN",
    "ACTOR_EN_TR",
    "ACTOR_BG_SPOT16_BOMBSTONE",
    "ACTOR_UNSET_CE",
    "ACTOR_BG_HIDAN_KOWARERUKABE",
    "ACTOR_BG_BOMBWALL",
    "ACTOR_BG_SPOT08_ICEBLOCK",
    "ACTOR_EN_RU2",
    "ACTOR_OBJ_DEKUJR",
    "ACTOR_BG_MIZU_UZU",
    "ACTOR_BG_SPOT06_OBJECTS",
    "ACTOR_BG_ICE_OBJECTS",
    "ACTOR_BG_HAKA_WATER",
    "ACTOR_UNSET_D8",
    "ACTOR_EN_MA2",
    "ACTOR_EN_BOM_CHU",
    "ACTOR_EN_HORSE_GAME_CHECK",
    "ACTOR_BOSS_TW",
    "ACTOR_EN_RR",
    "ACTOR_EN_BA",
    "ACTOR_EN_BX",
    "ACTOR_EN_ANUBICE",
    "ACTOR_EN_ANUBICE_FIRE",
    "ACTOR_BG_MORI_HASHIGO",
    "ACTOR_BG_MORI_HASHIRA4",
    "ACTOR_BG_MORI_IDOMIZU",
    "ACTOR_BG_SPOT16_DOUGHNUT",
    "ACTOR_BG_BDAN_SWITCH",
    "ACTOR_EN_MA1",
    "ACTOR_BOSS_GANON",
    "ACTOR_BOSS_SST",
    "ACTOR_UNSET_EA",
    "ACTOR_UNSET_EB",
    "ACTOR_EN_NY",
    "ACTOR_EN_FR",
    "ACTOR_ITEM_SHIELD",
    "ACTOR_BG_ICE_SHELTER",
    "ACTOR_EN_ICE_HONO",
    "ACTOR_ITEM_OCARINA",
    "ACTOR_UNSET_F2",
    "ACTOR_UNSET_F3",
    "ACTOR_MAGIC_DARK",
    "ACTOR_DEMO_6K",
    "ACTOR_EN_ANUBICE_TAG",
    "ACTOR_BG_HAKA_GATE",
    "ACTOR_BG_SPOT15_SAKU",
    "ACTOR_BG_JYA_GOROIWA",
    "ACTOR_BG_JYA_ZURERUKABE",
    "ACTOR_UNSET_FB",
    "ACTOR_BG_JYA_COBRA",
    "ACTOR_BG_JYA_KANAAMI",
    "ACTOR_FISHING",
    "ACTOR_OBJ_OSHIHIKI",
    "ACTOR_BG_GATE_SHUTTER",
    "ACTOR_EFF_DUST",
    "ACTOR_BG_SPOT01_FUSYA",
    "ACTOR_BG_SPOT01_IDOHASHIRA",
    "ACTOR_BG_SPOT01_IDOMIZU",
    "ACTOR_BG_PO_SYOKUDAI",
    "ACTOR_BG_GANON_OTYUKA",
    "ACTOR_BG_SPOT15_RRBOX",
    "ACTOR_BG_UMAJUMP",
    "ACTOR_UNSET_109",
    "ACTOR_ARROW_FIRE",
    "ACTOR_ARROW_ICE",
    "ACTOR_ARROW_LIGHT",
    "ACTOR_UNSET_10D",
    "ACTOR_UNSET_10E",
    "ACTOR_ITEM_ETCETERA",
    "ACTOR_OBJ_KIBAKO",
    "ACTOR_OBJ_TSUBO",
    "ACTOR_EN_WONDER_ITEM",
    "ACTOR_EN_IK",
    "ACTOR_DEMO_IK",
    "ACTOR_EN_SKJ",
    "ACTOR_EN_SKJNEEDLE",
    "ACTOR_EN_G_SWITCH",
    "ACTOR_DEMO_EXT",
    "ACTOR_DEMO_SHD",
    "ACTOR_EN_DNS",
    "ACTOR_ELF_MSG",
    "ACTOR_EN_HONOTRAP",
    "ACTOR_EN_TUBO_TRAP",
    "ACTOR_OBJ_ICE_POLY",
    "ACTOR_BG_SPOT03_TAKI",
    "ACTOR_BG_SPOT07_TAKI",
    "ACTOR_EN_FZ",
    "ACTOR_EN_PO_RELAY",
    "ACTOR_BG_RELAY_OBJECTS",
    "ACTOR_EN_DIVING_GAME",
    "ACTOR_EN_KUSA",
    "ACTOR_OBJ_BEAN",
    "ACTOR_OBJ_BOMBIWA",
    "ACTOR_UNSET_128",
    "ACTOR_UNSET_129",
    "ACTOR_OBJ_SWITCH",
    "ACTOR_OBJ_ELEVATOR",
    "ACTOR_OBJ_LIFT",
    "ACTOR_OBJ_HSBLOCK",
    "ACTOR_EN_OKARINA_TAG",
    "ACTOR_EN_YABUSAME_MARK",
    "ACTOR_EN_GOROIWA",
    "ACTOR_EN_EX_RUPPY",
    "ACTOR_EN_TORYO",
    "ACTOR_EN_DAIKU",
    "ACTOR_UNSET_134",
    "ACTOR_EN_NWC",
    "ACTOR_EN_BLKOBJ",
    "ACTOR_ITEM_INBOX",
    "ACTOR_EN_GE1",
    "ACTOR_OBJ_BLOCKSTOP",
    "ACTOR_EN_SDA",
    "ACTOR_EN_CLEAR_TAG",
    "ACTOR_EN_NIW_LADY",
    "ACTOR_EN_GM",
    "ACTOR_EN_MS",
    "ACTOR_EN_HS",
    "ACTOR_BG_INGATE",
    "ACTOR_EN_KANBAN",
    "ACTOR_EN_HEISHI3",
    "ACTOR_EN_SYATEKI_NIW",
    "ACTOR_EN_ATTACK_NIW",
    "ACTOR_BG_SPOT01_IDOSOKO",
    "ACTOR_EN_SA",
    "ACTOR_EN_WONDER_TALK",
    "ACTOR_BG_GJYO_BRIDGE",
    "ACTOR_EN_DS",
    "ACTOR_EN_MK",
    "ACTOR_EN_BOM_BOWL_MAN",
    "ACTOR_EN_BOM_BOWL_PIT",
    "ACTOR_EN_OWL",
    "ACTOR_EN_ISHI",
    "ACTOR_OBJ_HANA",
    "ACTOR_OBJ_LIGHTSWITCH",
    "ACTOR_OBJ_MURE2",
    "ACTOR_EN_GO",
    "ACTOR_EN_FU",
    "ACTOR_UNSET_154",
    "ACTOR_EN_CHANGER",
    "ACTOR_BG_JYA_MEGAMI",
    "ACTOR_BG_JYA_LIFT",
    "ACTOR_BG_JYA_BIGMIRROR",
    "ACTOR_BG_JYA_BOMBCHUIWA",
    "ACTOR_BG_JYA_AMISHUTTER",
    "ACTOR_BG_JYA_BOMBIWA",
    "ACTOR_BG_SPOT18_BASKET",
    "ACTOR_UNSET_15D",
    "ACTOR_EN_GANON_ORGAN",
    "ACTOR_EN_SIOFUKI",
    "ACTOR_EN_STREAM",
    "ACTOR_UNSET_161",
    "ACTOR_EN_MM",
    "ACTOR_EN_KO",
    "ACTOR_EN_KZ",
    "ACTOR_EN_WEATHER_TAG",
    "ACTOR_BG_SST_FLOOR",
    "ACTOR_EN_ANI",
    "ACTOR_EN_EX_ITEM",
    "ACTOR_BG_JYA_IRONOBJ",
    "ACTOR_EN_JS",
    "ACTOR_EN_JSJUTAN",
    "ACTOR_EN_CS",
    "ACTOR_EN_MD",
    "ACTOR_EN_HY",
    "ACTOR_EN_GANON_MANT",
    "ACTOR_EN_OKARINA_EFFECT",
    "ACTOR_EN_MAG",
    "ACTOR_DOOR_GERUDO",
    "ACTOR_ELF_MSG2",
    "ACTOR_DEMO_GT",
    "ACTOR_EN_PO_FIELD",
    "ACTOR_EFC_ERUPC",
    "ACTOR_BG_ZG",
    "ACTOR_EN_HEISHI4",
    "ACTOR_EN_ZL3",
    "ACTOR_BOSS_GANON2",
    "ACTOR_EN_KAKASI",
    "ACTOR_EN_TAKARA_MAN",
    "ACTOR_OBJ_MAKEOSHIHIKI",
    "ACTOR_OCEFF_SPOT",
    "ACTOR_END_TITLE",
    "ACTOR_UNSET_180",
    "ACTOR_EN_TORCH",
    "ACTOR_DEMO_EC",
    "ACTOR_SHOT_SUN",
    "ACTOR_EN_DY_EXTRA",
    "ACTOR_EN_WONDER_TALK2",
    "ACTOR_EN_GE2",
    "ACTOR_OBJ_ROOMTIMER",
    "ACTOR_EN_SSH",
    "ACTOR_EN_STH",
    "ACTOR_OCEFF_WIPE",
    "ACTOR_OCEFF_STORM",
    "ACTOR_EN_WEIYER",
    "ACTOR_BG_SPOT05_SOKO",
    "ACTOR_BG_JYA_1FLIFT",
    "ACTOR_BG_JYA_HAHENIRON",
    "ACTOR_BG_SPOT12_GATE",
    "ACTOR_BG_SPOT12_SAKU",
    "ACTOR_EN_HINTNUTS",
    "ACTOR_EN_NUTSBALL",
    "ACTOR_BG_SPOT00_BREAK",
    "ACTOR_EN_SHOPNUTS",
    "ACTOR_EN_IT",
    "ACTOR_EN_GELDB",
    "ACTOR_OCEFF_WIPE2",
    "ACTOR_OCEFF_WIPE3",
    "ACTOR_EN_NIW_GIRL",
    "ACTOR_EN_DOG",
    "ACTOR_EN_SI",
    "ACTOR_BG_SPOT01_OBJECTS2",
    "ACTOR_OBJ_COMB",
    "ACTOR_BG_SPOT11_BAKUDANKABE",
    "ACTOR_OBJ_KIBAKO2",
    "ACTOR_EN_DNT_DEMO",
    "ACTOR_EN_DNT_JIJI",
    "ACTOR_EN_DNT_NOMAL",
    "ACTOR_EN_GUEST",
    "ACTOR_BG_BOM_GUARD",
    "ACTOR_EN_HS2",
    "ACTOR_DEMO_KEKKAI",
    "ACTOR_BG_SPOT08_BAKUDANKABE",
    "ACTOR_BG_SPOT17_BAKUDANKABE",
    "ACTOR_UNSET_1AA",
    "ACTOR_OBJ_MURE3",
    "ACTOR_EN_TG",
    "ACTOR_EN_MU",
    "ACTOR_EN_GO2",
    "ACTOR_EN_WF",
    "ACTOR_EN_SKB",
    "ACTOR_DEMO_GJ",
    "ACTOR_DEMO_GEFF",
    "ACTOR_BG_GND_FIREMEIRO",
    "ACTOR_BG_GND_DARKMEIRO",
    "ACTOR_BG_GND_SOULMEIRO",
    "ACTOR_BG_GND_NISEKABE",
    "ACTOR_BG_GND_ICEBLOCK",
    "ACTOR_EN_GB",
    "ACTOR_EN_GS",
    "ACTOR_BG_MIZU_BWALL",
    "ACTOR_BG_MIZU_SHUTTER",
    "ACTOR_EN_DAIKU_KAKARIKO",
    "ACTOR_BG_BOWL_WALL",
    "ACTOR_EN_WALL_TUBO",
    "ACTOR_EN_PO_DESERT",
    "ACTOR_EN_CROW",
    "ACTOR_DOOR_KILLER",
    "ACTOR_BG_SPOT11_OASIS",
    "ACTOR_BG_SPOT18_FUTA",
    "ACTOR_BG_SPOT18_SHUTTER",
    "ACTOR_EN_MA3",
    "ACTOR_EN_COW",
    "ACTOR_BG_ICE_TURARA",
    "ACTOR_BG_ICE_SHUTTER",
    "ACTOR_EN_KAKASI2",
    "ACTOR_EN_KAKASI3",
    "ACTOR_OCEFF_WIPE4",
    "ACTOR_EN_EG",
    "ACTOR_BG_MENKURI_NISEKABE",
    "ACTOR_EN_ZO",
    "ACTOR_OBJ_MAKEKINSUTA",
    "ACTOR_EN_GE3",
    "ACTOR_OBJ_TIMEBLOCK",
    "ACTOR_OBJ_HAMISHI",
    "ACTOR_EN_ZL4",
    "ACTOR_EN_MM2",
    "ACTOR_BG_JYA_BLOCK",
    "ACTOR_OBJ_WARP2BLOCK",
    "ACTOR_1D7",
    "ACTOR_1D8",
    "ACTOR_1D9",
    "ACTOR_1DA",
    "ACTOR_ID_MAX",
)

objectsTable = (
    "OBJECT_UNSET_0",
    "OBJECT_GAMEPLAY_KEEP",
    "OBJECT_GAMEPLAY_FIELD_KEEP",
    "OBJECT_GAMEPLAY_DANGEON_KEEP",
    "OBJECT_UNSET_4",
    "OBJECT_UNSET_5",
    "OBJECT_HUMAN",
    "OBJECT_OKUTA",
    "OBJECT_CROW",
    "OBJECT_POH",
    "OBJECT_DY_OBJ",
    "OBJECT_WALLMASTER",
    "OBJECT_DODONGO",
    "OBJECT_FIREFLY",
    "OBJECT_BOX",
    "OBJECT_FIRE",
    "OBJECT_UNSET_10",
    "OBJECT_UNSET_11",
    "OBJECT_BUBBLE",
    "OBJECT_NIW",
    "OBJECT_LINK_BOY",
    "OBJECT_LINK_CHILD",
    "OBJECT_TITE",
    "OBJECT_REEBA",
    "OBJECT_PEEHAT",
    "OBJECT_KINGDODONGO",
    "OBJECT_HORSE",
    "OBJECT_ZF",
    "OBJECT_GOMA",
    "OBJECT_ZL1",
    "OBJECT_GOL",
    "OBJECT_DODOJR",
    "OBJECT_TORCH2",
    "OBJECT_BL",
    "OBJECT_TP",
    "OBJECT_OA1",
    "OBJECT_ST",
    "OBJECT_BW",
    "OBJECT_EI",
    "OBJECT_HORSE_NORMAL",
    "OBJECT_OB1",
    "OBJECT_O_ANIME",
    "OBJECT_SPOT04_OBJECTS",
    "OBJECT_DDAN_OBJECTS",
    "OBJECT_HIDAN_OBJECTS",
    "OBJECT_HORSE_GANON",
    "OBJECT_OA2",
    "OBJECT_SPOT00_OBJECTS",
    "OBJECT_MB",
    "OBJECT_BOMBF",
    "OBJECT_SK2",
    "OBJECT_OE1",
    "OBJECT_OE_ANIME",
    "OBJECT_OE2",
    "OBJECT_YDAN_OBJECTS",
    "OBJECT_GND",
    "OBJECT_AM",
    "OBJECT_DEKUBABA",
    "OBJECT_UNSET_3A",
    "OBJECT_OA3",
    "OBJECT_OA4",
    "OBJECT_OA5",
    "OBJECT_OA6",
    "OBJECT_OA7",
    "OBJECT_JJ",
    "OBJECT_OA8",
    "OBJECT_OA9",
    "OBJECT_OB2",
    "OBJECT_OB3",
    "OBJECT_OB4",
    "OBJECT_HORSE_ZELDA",
    "OBJECT_OPENING_DEMO1",
    "OBJECT_WARP1",
    "OBJECT_B_HEART",
    "OBJECT_DEKUNUTS",
    "OBJECT_OE3",
    "OBJECT_OE4",
    "OBJECT_MENKURI_OBJECTS",
    "OBJECT_OE5",
    "OBJECT_OE6",
    "OBJECT_OE7",
    "OBJECT_OE8",
    "OBJECT_OE9",
    "OBJECT_OE10",
    "OBJECT_OE11",
    "OBJECT_OE12",
    "OBJECT_VALI",
    "OBJECT_OA10",
    "OBJECT_OA11",
    "OBJECT_MIZU_OBJECTS",
    "OBJECT_FHG",
    "OBJECT_OSSAN",
    "OBJECT_MORI_HINERI1",
    "OBJECT_BB",
    "OBJECT_TOKI_OBJECTS",
    "OBJECT_YUKABYUN",
    "OBJECT_ZL2",
    "OBJECT_MJIN",
    "OBJECT_MJIN_FLASH",
    "OBJECT_MJIN_DARK",
    "OBJECT_MJIN_FLAME",
    "OBJECT_MJIN_ICE",
    "OBJECT_MJIN_SOUL",
    "OBJECT_MJIN_WIND",
    "OBJECT_MJIN_OKA",
    "OBJECT_HAKA_OBJECTS",
    "OBJECT_SPOT06_OBJECTS",
    "OBJECT_ICE_OBJECTS",
    "OBJECT_RELAY_OBJECTS",
    "OBJECT_PO_FIELD",
    "OBJECT_PO_COMPOSER",
    "OBJECT_MORI_HINERI1A",
    "OBJECT_MORI_HINERI2",
    "OBJECT_MORI_HINERI2A",
    "OBJECT_MORI_OBJECTS",
    "OBJECT_MORI_TEX",
    "OBJECT_SPOT08_OBJ",
    "OBJECT_WARP2",
    "OBJECT_HATA",
    "OBJECT_BIRD",
    "OBJECT_UNSET_78",
    "OBJECT_UNSET_79",
    "OBJECT_UNSET_7A",
    "OBJECT_UNSET_7B",
    "OBJECT_WOOD02",
    "OBJECT_UNSET_7D",
    "OBJECT_UNSET_7E",
    "OBJECT_UNSET_7F",
    "OBJECT_UNSET_80",
    "OBJECT_LIGHTBOX",
    "OBJECT_PU_BOX",
    "OBJECT_UNSET_83",
    "OBJECT_UNSET_84",
    "OBJECT_TRAP",
    "OBJECT_VASE",
    "OBJECT_IM",
    "OBJECT_TA",
    "OBJECT_TK",
    "OBJECT_XC",
    "OBJECT_VM",
    "OBJECT_BV",
    "OBJECT_HAKACH_OBJECTS",
    "OBJECT_EFC_CRYSTAL_LIGHT",
    "OBJECT_EFC_FIRE_BALL",
    "OBJECT_EFC_FLASH",
    "OBJECT_EFC_LGT_SHOWER",
    "OBJECT_EFC_STAR_FIELD",
    "OBJECT_GOD_LGT",
    "OBJECT_LIGHT_RING",
    "OBJECT_TRIFORCE_SPOT",
    "OBJECT_BDAN_OBJECTS",
    "OBJECT_SD",
    "OBJECT_RD",
    "OBJECT_PO_SISTERS",
    "OBJECT_HEAVY_OBJECT",
    "OBJECT_GNDD",
    "OBJECT_FD",
    "OBJECT_DU",
    "OBJECT_FW",
    "OBJECT_MEDAL",
    "OBJECT_HORSE_LINK_CHILD",
    "OBJECT_SPOT02_OBJECTS",
    "OBJECT_HAKA",
    "OBJECT_RU1",
    "OBJECT_SYOKUDAI",
    "OBJECT_FD2",
    "OBJECT_DH",
    "OBJECT_RL",
    "OBJECT_EFC_TW",
    "OBJECT_DEMO_TRE_LGT",
    "OBJECT_GI_KEY",
    "OBJECT_MIR_RAY",
    "OBJECT_BROB",
    "OBJECT_GI_JEWEL",
    "OBJECT_SPOT09_OBJ",
    "OBJECT_SPOT18_OBJ",
    "OBJECT_BDOOR",
    "OBJECT_SPOT17_OBJ",
    "OBJECT_SHOP_DUNGEN",
    "OBJECT_NB",
    "OBJECT_MO",
    "OBJECT_SB",
    "OBJECT_GI_MELODY",
    "OBJECT_GI_HEART",
    "OBJECT_GI_COMPASS",
    "OBJECT_GI_BOSSKEY",
    "OBJECT_GI_MEDAL",
    "OBJECT_GI_NUTS",
    "OBJECT_SA",
    "OBJECT_GI_HEARTS",
    "OBJECT_GI_ARROWCASE",
    "OBJECT_GI_BOMBPOUCH",
    "OBJECT_IN",
    "OBJECT_TR",
    "OBJECT_SPOT16_OBJ",
    "OBJECT_OE1S",
    "OBJECT_OE4S",
    "OBJECT_OS_ANIME",
    "OBJECT_GI_BOTTLE",
    "OBJECT_GI_STICK",
    "OBJECT_GI_MAP",
    "OBJECT_OF1D_MAP",
    "OBJECT_RU2",
    "OBJECT_GI_SHIELD_1",
    "OBJECT_DEKUJR",
    "OBJECT_GI_MAGICPOT",
    "OBJECT_GI_BOMB_1",
    "OBJECT_OF1S",
    "OBJECT_MA2",
    "OBJECT_GI_PURSE",
    "OBJECT_HNI",
    "OBJECT_TW",
    "OBJECT_RR",
    "OBJECT_BXA",
    "OBJECT_ANUBICE",
    "OBJECT_GI_GERUDO",
    "OBJECT_GI_ARROW",
    "OBJECT_GI_BOMB_2",
    "OBJECT_GI_EGG",
    "OBJECT_GI_SCALE",
    "OBJECT_GI_SHIELD_2",
    "OBJECT_GI_HOOKSHOT",
    "OBJECT_GI_OCARINA",
    "OBJECT_GI_MILK",
    "OBJECT_MA1",
    "OBJECT_GANON",
    "OBJECT_SST",
    "OBJECT_NY_UNUSED",
    "OBJECT_UNSET_E4",
    "OBJECT_NY",
    "OBJECT_FR",
    "OBJECT_GI_PACHINKO",
    "OBJECT_GI_BOOMERANG",
    "OBJECT_GI_BOW",
    "OBJECT_GI_GLASSES",
    "OBJECT_GI_LIQUID",
    "OBJECT_ANI",
    "OBJECT_DEMO_6K",
    "OBJECT_GI_SHIELD_3",
    "OBJECT_GI_LETTER",
    "OBJECT_SPOT15_OBJ",
    "OBJECT_JYA_OBJ",
    "OBJECT_GI_CLOTHES",
    "OBJECT_GI_BEAN",
    "OBJECT_GI_FISH",
    "OBJECT_GI_SAW",
    "OBJECT_GI_HAMMER",
    "OBJECT_GI_GRASS",
    "OBJECT_GI_LONGSWORD",
    "OBJECT_SPOT01_OBJECTS",
    "OBJECT_MD_UNUSED",
    "OBJECT_MD",
    "OBJECT_KM1",
    "OBJECT_KW1",
    "OBJECT_ZO",
    "OBJECT_KZ",
    "OBJECT_UMAJUMP",
    "OBJECT_MASTERKOKIRI",
    "OBJECT_MASTERKOKIRIHEAD",
    "OBJECT_MASTERGOLON",
    "OBJECT_MASTERZOORA",
    "OBJECT_AOB",
    "OBJECT_IK",
    "OBJECT_AHG",
    "OBJECT_CNE",
    "OBJECT_GI_NIWATORI",
    "OBJECT_SKJ",
    "OBJECT_GI_BOTTLE_LETTER",
    "OBJECT_BJI",
    "OBJECT_BBA",
    "OBJECT_GI_OCARINA_0",
    "OBJECT_DS",
    "OBJECT_ANE",
    "OBJECT_BOJ",
    "OBJECT_SPOT03_OBJECT",
    "OBJECT_SPOT07_OBJECT",
    "OBJECT_FZ",
    "OBJECT_BOB",
    "OBJECT_GE1",
    "OBJECT_YABUSAME_POINT",
    "OBJECT_GI_BOOTS_2",
    "OBJECT_GI_SEED",
    "OBJECT_GND_MAGIC",
    "OBJECT_D_ELEVATOR",
    "OBJECT_D_HSBLOCK",
    "OBJECT_D_LIFT",
    "OBJECT_MAMENOKI",
    "OBJECT_GOROIWA",
    "OBJECT_UNSET_120",
    "OBJECT_TORYO",
    "OBJECT_DAIKU",
    "OBJECT_UNSET_123",
    "OBJECT_NWC",
    "OBJECT_BLKOBJ",
    "OBJECT_GM",
    "OBJECT_MS",
    "OBJECT_HS",
    "OBJECT_INGATE",
    "OBJECT_LIGHTSWITCH",
    "OBJECT_KUSA",
    "OBJECT_TSUBO",
    "OBJECT_GI_GLOVES",
    "OBJECT_GI_COIN",
    "OBJECT_KANBAN",
    "OBJECT_GJYO_OBJECTS",
    "OBJECT_OWL",
    "OBJECT_MK",
    "OBJECT_FU",
    "OBJECT_GI_KI_TAN_MASK",
    "OBJECT_GI_REDEAD_MASK",
    "OBJECT_GI_SKJ_MASK",
    "OBJECT_GI_RABIT_MASK",
    "OBJECT_GI_TRUTH_MASK",
    "OBJECT_GANON_OBJECTS",
    "OBJECT_SIOFUKI",
    "OBJECT_STREAM",
    "OBJECT_MM",
    "OBJECT_FA",
    "OBJECT_OS",
    "OBJECT_GI_EYE_LOTION",
    "OBJECT_GI_POWDER",
    "OBJECT_GI_MUSHROOM",
    "OBJECT_GI_TICKETSTONE",
    "OBJECT_GI_BROKENSWORD",
    "OBJECT_JS",
    "OBJECT_CS",
    "OBJECT_GI_PRESCRIPTION",
    "OBJECT_GI_BRACELET",
    "OBJECT_GI_SOLDOUT",
    "OBJECT_GI_FROG",
    "OBJECT_MAG",
    "OBJECT_DOOR_GERUDO",
    "OBJECT_GT",
    "OBJECT_EFC_ERUPC",
    "OBJECT_ZL2_ANIME1",
    "OBJECT_ZL2_ANIME2",
    "OBJECT_GI_GOLONMASK",
    "OBJECT_GI_ZORAMASK",
    "OBJECT_GI_GERUDOMASK",
    "OBJECT_GANON2",
    "OBJECT_KA",
    "OBJECT_TS",
    "OBJECT_ZG",
    "OBJECT_GI_HOVERBOOTS",
    "OBJECT_GI_M_ARROW",
    "OBJECT_DS2",
    "OBJECT_EC",
    "OBJECT_FISH",
    "OBJECT_GI_SUTARU",
    "OBJECT_GI_GODDESS",
    "OBJECT_SSH",
    "OBJECT_BIGOKUTA",
    "OBJECT_BG",
    "OBJECT_SPOT05_OBJECTS",
    "OBJECT_SPOT12_OBJ",
    "OBJECT_BOMBIWA",
    "OBJECT_HINTNUTS",
    "OBJECT_RS",
    "OBJECT_SPOT00_BREAK",
    "OBJECT_GLA",
    "OBJECT_SHOPNUTS",
    "OBJECT_GELDB",
    "OBJECT_GR",
    "OBJECT_DOG",
    "OBJECT_JYA_IRON",
    "OBJECT_JYA_DOOR",
    "OBJECT_UNSET_16E",
    "OBJECT_SPOT11_OBJ",
    "OBJECT_KIBAKO2",
    "OBJECT_DNS",
    "OBJECT_DNK",
    "OBJECT_GI_FIRE",
    "OBJECT_GI_INSECT",
    "OBJECT_GI_BUTTERFLY",
    "OBJECT_GI_GHOST",
    "OBJECT_GI_SOUL",
    "OBJECT_BOWL",
    "OBJECT_DEMO_KEKKAI",
    "OBJECT_EFC_DOUGHNUT",
    "OBJECT_GI_DEKUPOUCH",
    "OBJECT_GANON_ANIME1",
    "OBJECT_GANON_ANIME2",
    "OBJECT_GANON_ANIME3",
    "OBJECT_GI_RUPY",
    "OBJECT_SPOT01_MATOYA",
    "OBJECT_SPOT01_MATOYAB",
    "OBJECT_MU",
    "OBJECT_WF",
    "OBJECT_SKB",
    "OBJECT_GJ",
    "OBJECT_GEFF",
    "OBJECT_HAKA_DOOR",
    "OBJECT_GS",
    "OBJECT_PS",
    "OBJECT_BWALL",
    "OBJECT_COW",
    "OBJECT_COB",
    "OBJECT_GI_SWORD_1",
    "OBJECT_DOOR_KILLER",
    "OBJECT_OUKE_HAKA",
    "OBJECT_TIMEBLOCK",
    "OBJECT_ZL4",
    "OBJECT_GANON_DOWN",
    "OBJECT_GANON_DEMO",
    "OBJECT_HINTSTONE",
    "OBJECT_GI_SWORD_2",
    "OBJECT_GI_FIRE_ARROW",
    "OBJECT_GI_ICE_ARROW",
    "OBJECT_GI_LIGHT_ARROW",
    "OBJECT_GI_M_LIQUID",
    "OBJECT_GI_BIGGHOST",
    "OBJECT_GI_NONE",
    "OBJECT_GI_JADE",
    "OBJECT_GI_RUBY",
    "OBJECT_GI_SAPPHIRE",
    "OBJECT_LINK_OPENING",
    "OBJECT_KEEP_OPENING",
    "OBJECT_ID_MAX",
)

actorCategories = ("ACTORCAT_SWITCH", "ACTORCAT_BG", "ACTORCAT_PLAYER",
    "ACTORCAT_EXPLOSIVES", "ACTORCAT_NPC", "ACTORCAT_ENEMY", "ACTORCAT_PROP",
    "ACTORCAT_ITEMACTION", "ACTORCAT_MISC", "ACTORCAT_BOSS", "ACTORCAT_DOOR", "ACTORCAT_CHEST")

code = open('baserom/exefs/code.bin', 'r+b')

def vAddrToPAddr(vAddr):
    return vAddr - 0x100000

def getActorSize(actorId):
    code.seek(vAddrToPAddr(gActorOverlayTableVAddr) + (actorId * 0x20) + 0x14)
    actorInitInfoVAddr = struct.unpack('<i', code.read(4))[0]
    code.seek(vAddrToPAddr(actorInitInfoVAddr) + 0xC)
    actorSize = struct.unpack('<i', code.read(4))[0]
    return actorSize

# typedef struct {
#     /* 0x00 */ s16 id;
#     /* 0x02 */ u8  type; // Classifies actor and determines when actor will execute
#     /* 0x04 */ u32 flags;
#     /* 0x08 */ s16 objectId;
#     /* 0x0C */ u32 instanceSize;
#     /* 0x10 */ ActorFunc init; // Constructor
#     /* 0x14 */ ActorFunc destroy; // Destructor
#     /* 0x18 */ ActorFunc update; // Main Update Function
#     /* 0x1C */ ActorFunc draw; // Draw function
# } ActorInit; // size = 0x20

def getActorInitVars(actorId):
    code.seek(vAddrToPAddr(gActorOverlayTableVAddr) + (actorId * 0x20) + 0x14)
    actorInitInfoVAddr = struct.unpack('<i', code.read(4))[0]
    code.seek(vAddrToPAddr(actorInitInfoVAddr))
    id = struct.unpack('<h', code.read(2))[0]
    type = struct.unpack('<B', code.read(1))[0]
    pad = struct.unpack('<b', code.read(1))[0]
    flags = struct.unpack('<I', code.read(4))[0]
    objectId = struct.unpack('<h', code.read(2))[0]
    pad = struct.unpack('<h', code.read(2))[0]
    instanceSize = struct.unpack('<I', code.read(4))[0]
    init = struct.unpack('<I', code.read(4))[0]
    destroy = struct.unpack('<I', code.read(4))[0]
    update = struct.unpack('<I', code.read(4))[0]
    draw = struct.unpack('<I', code.read(4))[0]
    return (id, type, flags, objectId, instanceSize, init, destroy, update, draw)

def createActorHeader(path, actorName, actorId):
    actorStructName = actorName.replace("_","")
    actorSize = getActorSize(actorId)

    fileStr = "#ifndef _Z_" + actorName.upper() + "_H_\n"
    fileStr += "#define _Z_" + actorName.upper() + "_H_\n"
    fileStr += "\n"
    fileStr += "#include \"global.hpp\"\n"
    fileStr += "\n"
    fileStr += "struct " + actorStructName + ";\n"
    fileStr += "\n"
    fileStr += "typedef struct " + actorStructName + " {\n"
    fileStr += "    /* 0x0000 */ Actor actor;\n"
    if actorSize > 0x1A4:
        fileStr += "    /* 0x01A4 */ char unk_1A4[" + "0x{:X}".format(actorSize - 0x1A4) + "];\n"
    fileStr += "} " + actorStructName + "; // size = " + "0x{:X}".format(actorSize) + "\n"
    fileStr += "\n"
    fileStr += "extern ActorInit " + actorName + "_InitVars;\n"
    fileStr += "\n"
    fileStr += "#endif\n"

    with open(path, 'w') as header:
        header.write(fileStr)

def createActorSource(path, actorName, actorId):
    addrs = open('function_addresses_new.txt', 'r')
    funcs = addrs.read()

    linkerFile = open('oot_new.ld', 'r')
    linker = linkerFile.read()

    functionNamesToRemove = []

    actorStructName = actorName.replace("_","")
    initVars = getActorInitVars(actorId)

    fileStr = "extern \"C\" {\n"
    if actorId != 0:
        fileStr += "#include \"z_" + actorName.lower() + ".hpp\"\n"
    else:
        fileStr += "#include \"global.hpp\""
    fileStr += "\n"
    fileStr += "#define FLAGS 0x{:08X}\n".format(initVars[2])
    fileStr += "\n"
    if (initVars[5] != 0):
        fileStr += "void " + actorStructName + "_Init(Actor* actor, GameState* state);\n"
    if (initVars[6] != 0):
        fileStr += "void " + actorStructName + "_Destroy(Actor* actor, GameState* state);\n"
    if (initVars[7] != 0):
        fileStr += "void " + actorStructName + "_Update(Actor* actor, GameState* state);\n"
    if (initVars[8] != 0):
        fileStr += "void " + actorStructName + "_Draw(Actor* actor, GameState* state);\n"
    fileStr += "\n"
    fileStr += "/*\n"
    fileStr += "ActorInit " + actorName + "_InitVars = {\n"
    fileStr += "    " + actorsTable[initVars[0]] + ",\n"
    fileStr += "    " + actorCategories[initVars[1]] +",\n"
    fileStr += "    FLAGS,\n"
    fileStr += "    " + objectsTable[initVars[3]] + ",\n"
    fileStr += "    sizeof(" + actorStructName + "),\n"
    if (initVars[5] != 0):
        fileStr += "    (ActorFunc)" + actorStructName + "_Init,\n"
    else:
        fileStr += "    (ActorFunc)NULL,\n"
    if (initVars[6] != 0):
        fileStr += "    (ActorFunc)" + actorStructName + "_Destroy,\n"
    else:
        fileStr += "    (ActorFunc)NULL,\n"
    if (initVars[7] != 0):
        fileStr += "    (ActorFunc)" + actorStructName + "_Update,\n"
    else:
        fileStr += "    (ActorFunc)NULL,\n"
    if (initVars[8] != 0):
        fileStr += "    (ActorFunc)" + actorStructName + "_Draw,\n"
    else:
        fileStr += "    (ActorFunc)NULL,\n"
    fileStr += "};\n"
    fileStr += "*/\n"

    if (initVars[5] != 0):
        fileStr += "\n#pragma GLOBAL_ASM(\"binary/" + actorStructName + "_Init.o\")\n"
        functionNamesToRemove.append("#pragma GLOBAL_ASM(\"binary/" + actorStructName + "_Init.o\")\n")
        functionNamesToRemove.append("#pragma GLOBAL_ASM(\"binary/" + "FUN_" + "{:08x}".format(initVars[5]) + ".o\")\n")
        funcs = funcs.replace("FUN_" + "{:08x}".format(initVars[5]), actorStructName + "_Init")
        linker = linker.replace("FUN_" + "{:08x}".format(initVars[5]), actorStructName + "_Init")
    if (initVars[6] != 0):
        fileStr += "\n#pragma GLOBAL_ASM(\"binary/" + actorStructName + "_Destroy.o\")\n"
        functionNamesToRemove.append("#pragma GLOBAL_ASM(\"binary/" + actorStructName + "_Destroy.o\")\n")
        functionNamesToRemove.append("#pragma GLOBAL_ASM(\"binary/" + "FUN_" + "{:08x}".format(initVars[6]) + ".o\")\n")
        funcs = funcs.replace("FUN_" + "{:08x}".format(initVars[6]), actorStructName + "_Destroy")
        linker = linker.replace("FUN_" + "{:08x}".format(initVars[6]), actorStructName + "_Destroy")
    if (initVars[7] != 0):
        fileStr += "\n#pragma GLOBAL_ASM(\"binary/" + actorStructName + "_Update.o\")\n"
        functionNamesToRemove.append("#pragma GLOBAL_ASM(\"binary/" + actorStructName + "_Update.o\")\n")
        functionNamesToRemove.append("#pragma GLOBAL_ASM(\"binary/" + "FUN_" + "{:08x}".format(initVars[7]) + ".o\")\n")
        funcs = funcs.replace("FUN_" + "{:08x}".format(initVars[7]), actorStructName + "_Update")
        linker = linker.replace("FUN_" + "{:08x}".format(initVars[7]), actorStructName + "_Update")
    if (initVars[8] != 0):
        fileStr += "\n#pragma GLOBAL_ASM(\"binary/" + actorStructName + "_Draw.o\")\n"
        functionNamesToRemove.append("#pragma GLOBAL_ASM(\"binary/" + actorStructName + "_Draw.o\")\n")
        functionNamesToRemove.append("#pragma GLOBAL_ASM(\"binary/" + "FUN_" + "{:08x}".format(initVars[8]) + ".o\")\n")
        funcs = funcs.replace("FUN_" + "{:08x}".format(initVars[8]), actorStructName + "_Draw")
        linker = linker.replace("FUN_" + "{:08x}".format(initVars[8]), actorStructName + "_Draw")

    addrs.close()
    with open('function_addresses_new.txt', 'w') as newFuncs:
        newFuncs.write(funcs)
    linkerFile.close()
    with open('oot_new.ld', 'w') as newLinker:
        newLinker.write(linker)

    fileStr += "}\n"

    with open('funcsToRemove.txt', 'a') as removes:
        for func in functionNamesToRemove:
            removes.write(func)

    with open(path, 'w') as source:
        source.write(fileStr)

with open('notes/actor_list.txt', 'r') as actorList:
    actorLines = actorList.readlines()
    for i in range(0, len(actorLines)):
        actorName = actorLines[i].strip()
        if actorName == "unset":
            continue
        if actorName == "Obj_Bombiwa" or actorName == "En_OE2" or actorName == "En_Torch" or actorName == "Bg_Gnd_Nisekabe" or actorName == "En_Vase":
            continue

        actorFolder = actorsFolder + actorName
        if not os.path.isdir(actorFolder):
            os.mkdir(actorFolder)

        actorSourceName = "z_" + actorName.lower()
        actorSourcePath = actorFolder + "/" + actorSourceName
        if not os.path.isfile(actorSourcePath + ".hpp") and i != 0:
            createActorHeader(actorSourcePath + ".hpp", actorName, i)

        if not os.path.isfile(actorSourcePath + ".cpp"):
            createActorSource(actorSourcePath + ".cpp", actorName, i)

code.close()
